schema_version = "1.0.0"

id = "looking_glass_display_simulator"
version = "1.0.0"
name = "Looking Glass Display Simulator"
tagline = "Simulate Looking Glass displays, create compatible quilts"
maintainer = "Lukáš Vincenc"
type = "add-on"
website = "https://github.com/lukas-vincenc/looking_glass_display_simulator"
blender_version_min = "5.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
files = "Import/export image files from/to disk"
